#!/groovy

@Library('jenkins-shared-library') _


pipeline {
    agent { node { label 'AGENT-1'} }

    stages {
        stage("Checkout") {
            //dir('catalogue') {
            steps {
                javaEKS()

                }
                
            }
        }
}